// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OptionWrapper.proto

package de.mid.smartfacts.bpm.dtos.wrapper.v1;

public final class OptionWrapper {
  private OptionWrapper() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OptionalStringOrBuilder extends
      // @@protoc_insertion_point(interface_extends:de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionalString)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string value = 1;</code>
     */
    java.lang.String getValue();
    /**
     * <code>string value = 1;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionalString}
   */
  public  static final class OptionalString extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionalString)
      OptionalStringOrBuilder {
    // Use OptionalString.newBuilder() to construct.
    private OptionalString(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OptionalString() {
      value_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private OptionalString(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              value_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.internal_static_de_mid_smartfacts_bpm_dtos_wrapper_v1_OptionalString_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.internal_static_de_mid_smartfacts_bpm_dtos_wrapper_v1_OptionalString_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalString.class, de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalString.Builder.class);
    }

    public static final int VALUE_FIELD_NUMBER = 1;
    private volatile java.lang.Object value_;
    /**
     * <code>string value = 1;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      }
    }
    /**
     * <code>string value = 1;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getValueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, value_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getValueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, value_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalString)) {
        return super.equals(obj);
      }
      de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalString other = (de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalString) obj;

      boolean result = true;
      result = result && getValue()
          .equals(other.getValue());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalString parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalString parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalString parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalString parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalString parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalString parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalString parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalString parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalString parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalString parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalString parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalString parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalString prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionalString}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionalString)
        de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalStringOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.internal_static_de_mid_smartfacts_bpm_dtos_wrapper_v1_OptionalString_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.internal_static_de_mid_smartfacts_bpm_dtos_wrapper_v1_OptionalString_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalString.class, de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalString.Builder.class);
      }

      // Construct using de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalString.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        value_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.internal_static_de_mid_smartfacts_bpm_dtos_wrapper_v1_OptionalString_descriptor;
      }

      public de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalString getDefaultInstanceForType() {
        return de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalString.getDefaultInstance();
      }

      public de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalString build() {
        de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalString result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalString buildPartial() {
        de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalString result = new de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalString(this);
        result.value_ = value_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalString) {
          return mergeFrom((de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalString)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalString other) {
        if (other == de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalString.getDefaultInstance()) return this;
        if (!other.getValue().isEmpty()) {
          value_ = other.value_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalString parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalString) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>string value = 1;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string value = 1;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string value = 1;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string value = 1;</code>
       */
      public Builder clearValue() {
        
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>string value = 1;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        value_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionalString)
    }

    // @@protoc_insertion_point(class_scope:de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionalString)
    private static final de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalString DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalString();
    }

    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalString getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OptionalString>
        PARSER = new com.google.protobuf.AbstractParser<OptionalString>() {
      public OptionalString parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new OptionalString(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OptionalString> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OptionalString> getParserForType() {
      return PARSER;
    }

    public de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalString getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OptionalInt32OrBuilder extends
      // @@protoc_insertion_point(interface_extends:de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionalInt32)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 value = 1;</code>
     */
    int getValue();
  }
  /**
   * Protobuf type {@code de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionalInt32}
   */
  public  static final class OptionalInt32 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionalInt32)
      OptionalInt32OrBuilder {
    // Use OptionalInt32.newBuilder() to construct.
    private OptionalInt32(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OptionalInt32() {
      value_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private OptionalInt32(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              value_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.internal_static_de_mid_smartfacts_bpm_dtos_wrapper_v1_OptionalInt32_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.internal_static_de_mid_smartfacts_bpm_dtos_wrapper_v1_OptionalInt32_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt32.class, de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt32.Builder.class);
    }

    public static final int VALUE_FIELD_NUMBER = 1;
    private int value_;
    /**
     * <code>int32 value = 1;</code>
     */
    public int getValue() {
      return value_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (value_ != 0) {
        output.writeInt32(1, value_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (value_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, value_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt32)) {
        return super.equals(obj);
      }
      de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt32 other = (de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt32) obj;

      boolean result = true;
      result = result && (getValue()
          == other.getValue());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt32 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt32 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt32 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt32 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt32 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt32 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt32 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt32 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt32 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt32 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt32 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt32 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt32 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionalInt32}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionalInt32)
        de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt32OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.internal_static_de_mid_smartfacts_bpm_dtos_wrapper_v1_OptionalInt32_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.internal_static_de_mid_smartfacts_bpm_dtos_wrapper_v1_OptionalInt32_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt32.class, de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt32.Builder.class);
      }

      // Construct using de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt32.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        value_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.internal_static_de_mid_smartfacts_bpm_dtos_wrapper_v1_OptionalInt32_descriptor;
      }

      public de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt32 getDefaultInstanceForType() {
        return de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt32.getDefaultInstance();
      }

      public de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt32 build() {
        de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt32 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt32 buildPartial() {
        de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt32 result = new de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt32(this);
        result.value_ = value_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt32) {
          return mergeFrom((de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt32)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt32 other) {
        if (other == de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt32.getDefaultInstance()) return this;
        if (other.getValue() != 0) {
          setValue(other.getValue());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt32 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt32) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int value_ ;
      /**
       * <code>int32 value = 1;</code>
       */
      public int getValue() {
        return value_;
      }
      /**
       * <code>int32 value = 1;</code>
       */
      public Builder setValue(int value) {
        
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 value = 1;</code>
       */
      public Builder clearValue() {
        
        value_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionalInt32)
    }

    // @@protoc_insertion_point(class_scope:de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionalInt32)
    private static final de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt32 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt32();
    }

    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt32 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OptionalInt32>
        PARSER = new com.google.protobuf.AbstractParser<OptionalInt32>() {
      public OptionalInt32 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new OptionalInt32(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OptionalInt32> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OptionalInt32> getParserForType() {
      return PARSER;
    }

    public de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt32 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OptionalInt64OrBuilder extends
      // @@protoc_insertion_point(interface_extends:de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionalInt64)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 value = 1;</code>
     */
    long getValue();
  }
  /**
   * Protobuf type {@code de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionalInt64}
   */
  public  static final class OptionalInt64 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionalInt64)
      OptionalInt64OrBuilder {
    // Use OptionalInt64.newBuilder() to construct.
    private OptionalInt64(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OptionalInt64() {
      value_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private OptionalInt64(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              value_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.internal_static_de_mid_smartfacts_bpm_dtos_wrapper_v1_OptionalInt64_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.internal_static_de_mid_smartfacts_bpm_dtos_wrapper_v1_OptionalInt64_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt64.class, de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt64.Builder.class);
    }

    public static final int VALUE_FIELD_NUMBER = 1;
    private long value_;
    /**
     * <code>int64 value = 1;</code>
     */
    public long getValue() {
      return value_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (value_ != 0L) {
        output.writeInt64(1, value_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (value_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, value_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt64)) {
        return super.equals(obj);
      }
      de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt64 other = (de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt64) obj;

      boolean result = true;
      result = result && (getValue()
          == other.getValue());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getValue());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt64 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt64 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt64 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt64 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt64 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt64 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt64 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt64 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt64 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt64 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt64 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt64 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt64 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionalInt64}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionalInt64)
        de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt64OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.internal_static_de_mid_smartfacts_bpm_dtos_wrapper_v1_OptionalInt64_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.internal_static_de_mid_smartfacts_bpm_dtos_wrapper_v1_OptionalInt64_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt64.class, de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt64.Builder.class);
      }

      // Construct using de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt64.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        value_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.internal_static_de_mid_smartfacts_bpm_dtos_wrapper_v1_OptionalInt64_descriptor;
      }

      public de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt64 getDefaultInstanceForType() {
        return de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt64.getDefaultInstance();
      }

      public de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt64 build() {
        de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt64 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt64 buildPartial() {
        de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt64 result = new de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt64(this);
        result.value_ = value_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt64) {
          return mergeFrom((de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt64)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt64 other) {
        if (other == de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt64.getDefaultInstance()) return this;
        if (other.getValue() != 0L) {
          setValue(other.getValue());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt64 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt64) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long value_ ;
      /**
       * <code>int64 value = 1;</code>
       */
      public long getValue() {
        return value_;
      }
      /**
       * <code>int64 value = 1;</code>
       */
      public Builder setValue(long value) {
        
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 value = 1;</code>
       */
      public Builder clearValue() {
        
        value_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionalInt64)
    }

    // @@protoc_insertion_point(class_scope:de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionalInt64)
    private static final de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt64 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt64();
    }

    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt64 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OptionalInt64>
        PARSER = new com.google.protobuf.AbstractParser<OptionalInt64>() {
      public OptionalInt64 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new OptionalInt64(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OptionalInt64> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OptionalInt64> getParserForType() {
      return PARSER;
    }

    public de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalInt64 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OptionalBoolOrBuilder extends
      // @@protoc_insertion_point(interface_extends:de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionalBool)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool value = 1;</code>
     */
    boolean getValue();
  }
  /**
   * Protobuf type {@code de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionalBool}
   */
  public  static final class OptionalBool extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionalBool)
      OptionalBoolOrBuilder {
    // Use OptionalBool.newBuilder() to construct.
    private OptionalBool(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OptionalBool() {
      value_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private OptionalBool(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              value_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.internal_static_de_mid_smartfacts_bpm_dtos_wrapper_v1_OptionalBool_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.internal_static_de_mid_smartfacts_bpm_dtos_wrapper_v1_OptionalBool_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBool.class, de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBool.Builder.class);
    }

    public static final int VALUE_FIELD_NUMBER = 1;
    private boolean value_;
    /**
     * <code>bool value = 1;</code>
     */
    public boolean getValue() {
      return value_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (value_ != false) {
        output.writeBool(1, value_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (value_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, value_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBool)) {
        return super.equals(obj);
      }
      de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBool other = (de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBool) obj;

      boolean result = true;
      result = result && (getValue()
          == other.getValue());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getValue());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBool parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBool parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBool parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBool parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBool parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBool parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBool parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBool parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBool parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBool parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBool parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBool parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBool prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionalBool}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionalBool)
        de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBoolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.internal_static_de_mid_smartfacts_bpm_dtos_wrapper_v1_OptionalBool_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.internal_static_de_mid_smartfacts_bpm_dtos_wrapper_v1_OptionalBool_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBool.class, de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBool.Builder.class);
      }

      // Construct using de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBool.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        value_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.internal_static_de_mid_smartfacts_bpm_dtos_wrapper_v1_OptionalBool_descriptor;
      }

      public de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBool getDefaultInstanceForType() {
        return de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBool.getDefaultInstance();
      }

      public de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBool build() {
        de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBool result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBool buildPartial() {
        de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBool result = new de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBool(this);
        result.value_ = value_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBool) {
          return mergeFrom((de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBool)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBool other) {
        if (other == de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBool.getDefaultInstance()) return this;
        if (other.getValue() != false) {
          setValue(other.getValue());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBool parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBool) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean value_ ;
      /**
       * <code>bool value = 1;</code>
       */
      public boolean getValue() {
        return value_;
      }
      /**
       * <code>bool value = 1;</code>
       */
      public Builder setValue(boolean value) {
        
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool value = 1;</code>
       */
      public Builder clearValue() {
        
        value_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionalBool)
    }

    // @@protoc_insertion_point(class_scope:de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionalBool)
    private static final de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBool DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBool();
    }

    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBool getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OptionalBool>
        PARSER = new com.google.protobuf.AbstractParser<OptionalBool>() {
      public OptionalBool parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new OptionalBool(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OptionalBool> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OptionalBool> getParserForType() {
      return PARSER;
    }

    public de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBool getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OptionalBytesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionalBytes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes value = 1;</code>
     */
    com.google.protobuf.ByteString getValue();
  }
  /**
   * Protobuf type {@code de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionalBytes}
   */
  public  static final class OptionalBytes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionalBytes)
      OptionalBytesOrBuilder {
    // Use OptionalBytes.newBuilder() to construct.
    private OptionalBytes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OptionalBytes() {
      value_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private OptionalBytes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              value_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.internal_static_de_mid_smartfacts_bpm_dtos_wrapper_v1_OptionalBytes_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.internal_static_de_mid_smartfacts_bpm_dtos_wrapper_v1_OptionalBytes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBytes.class, de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBytes.Builder.class);
    }

    public static final int VALUE_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString value_;
    /**
     * <code>bytes value = 1;</code>
     */
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!value_.isEmpty()) {
        output.writeBytes(1, value_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!value_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, value_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBytes)) {
        return super.equals(obj);
      }
      de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBytes other = (de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBytes) obj;

      boolean result = true;
      result = result && getValue()
          .equals(other.getValue());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBytes parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBytes parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBytes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBytes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBytes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBytes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBytes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBytes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBytes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBytes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBytes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBytes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBytes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionalBytes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionalBytes)
        de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBytesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.internal_static_de_mid_smartfacts_bpm_dtos_wrapper_v1_OptionalBytes_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.internal_static_de_mid_smartfacts_bpm_dtos_wrapper_v1_OptionalBytes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBytes.class, de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBytes.Builder.class);
      }

      // Construct using de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBytes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        value_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.internal_static_de_mid_smartfacts_bpm_dtos_wrapper_v1_OptionalBytes_descriptor;
      }

      public de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBytes getDefaultInstanceForType() {
        return de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBytes.getDefaultInstance();
      }

      public de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBytes build() {
        de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBytes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBytes buildPartial() {
        de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBytes result = new de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBytes(this);
        result.value_ = value_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBytes) {
          return mergeFrom((de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBytes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBytes other) {
        if (other == de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBytes.getDefaultInstance()) return this;
        if (other.getValue() != com.google.protobuf.ByteString.EMPTY) {
          setValue(other.getValue());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBytes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBytes) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes value = 1;</code>
       */
      public com.google.protobuf.ByteString getValue() {
        return value_;
      }
      /**
       * <code>bytes value = 1;</code>
       */
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes value = 1;</code>
       */
      public Builder clearValue() {
        
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionalBytes)
    }

    // @@protoc_insertion_point(class_scope:de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionalBytes)
    private static final de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBytes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBytes();
    }

    public static de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBytes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OptionalBytes>
        PARSER = new com.google.protobuf.AbstractParser<OptionalBytes>() {
      public OptionalBytes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new OptionalBytes(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OptionalBytes> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OptionalBytes> getParserForType() {
      return PARSER;
    }

    public de.mid.smartfacts.bpm.dtos.wrapper.v1.OptionWrapper.OptionalBytes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_de_mid_smartfacts_bpm_dtos_wrapper_v1_OptionalString_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_de_mid_smartfacts_bpm_dtos_wrapper_v1_OptionalString_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_de_mid_smartfacts_bpm_dtos_wrapper_v1_OptionalInt32_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_de_mid_smartfacts_bpm_dtos_wrapper_v1_OptionalInt32_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_de_mid_smartfacts_bpm_dtos_wrapper_v1_OptionalInt64_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_de_mid_smartfacts_bpm_dtos_wrapper_v1_OptionalInt64_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_de_mid_smartfacts_bpm_dtos_wrapper_v1_OptionalBool_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_de_mid_smartfacts_bpm_dtos_wrapper_v1_OptionalBool_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_de_mid_smartfacts_bpm_dtos_wrapper_v1_OptionalBytes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_de_mid_smartfacts_bpm_dtos_wrapper_v1_OptionalBytes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023OptionWrapper.proto\022%de.mid.smartfacts" +
      ".bpm.dtos.wrapper.v1\"\037\n\016OptionalString\022\r" +
      "\n\005value\030\001 \001(\t\"\036\n\rOptionalInt32\022\r\n\005value\030" +
      "\001 \001(\005\"\036\n\rOptionalInt64\022\r\n\005value\030\001 \001(\003\"\035\n" +
      "\014OptionalBool\022\r\n\005value\030\001 \001(\010\"\036\n\rOptional" +
      "Bytes\022\r\n\005value\030\001 \001(\014b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_de_mid_smartfacts_bpm_dtos_wrapper_v1_OptionalString_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_de_mid_smartfacts_bpm_dtos_wrapper_v1_OptionalString_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_de_mid_smartfacts_bpm_dtos_wrapper_v1_OptionalString_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_de_mid_smartfacts_bpm_dtos_wrapper_v1_OptionalInt32_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_de_mid_smartfacts_bpm_dtos_wrapper_v1_OptionalInt32_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_de_mid_smartfacts_bpm_dtos_wrapper_v1_OptionalInt32_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_de_mid_smartfacts_bpm_dtos_wrapper_v1_OptionalInt64_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_de_mid_smartfacts_bpm_dtos_wrapper_v1_OptionalInt64_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_de_mid_smartfacts_bpm_dtos_wrapper_v1_OptionalInt64_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_de_mid_smartfacts_bpm_dtos_wrapper_v1_OptionalBool_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_de_mid_smartfacts_bpm_dtos_wrapper_v1_OptionalBool_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_de_mid_smartfacts_bpm_dtos_wrapper_v1_OptionalBool_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_de_mid_smartfacts_bpm_dtos_wrapper_v1_OptionalBytes_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_de_mid_smartfacts_bpm_dtos_wrapper_v1_OptionalBytes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_de_mid_smartfacts_bpm_dtos_wrapper_v1_OptionalBytes_descriptor,
        new java.lang.String[] { "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
